# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "go-k8s"
  path         = "go/k8s"
}

created_at    = "2026-08-16T17:49:28.448529Z"
last_synced   = "2026-08-16T17:49:28.448529Z"
forge_version = "0.8.0"

variables {
  container_registry          = "ghcr"
  enable_helm_docs            = true
  enable_monitoring           = true
  git_host                    = "github.com"
  go_version                  = "1.26.6"
  license                     = "Apache-2.0"
  project_component_lifecycle = "production"
  project_component_owner     = "donaldgifford"
  project_component_system    = "infrastructure"
  project_component_type      = "service"
  project_description         = "Homelab Service"
  project_name                = "hoomlab"
  project_org                 = "donaldgifford"
  project_owner               = "donaldgifford"
  renovate_config_prefix      = "github"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:55c9690e6b9fb691a757945053cbea31d84a658afb6f983b68bc1685a18e0d65"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:dbadd93546136b41d8bdcc5bbf14b34a8c4c6cc3298ac2283bfec1be24fb1da5"
}

default ".github/CODEOWNERS" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:666453f28d6c351868d33031fd710f5ebab775b7dab797694b23eb587e161a4a"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4116d94fbad5355f4422bd9db3d7f1ba28126cb017f1125f6e55af967dc5b7bb"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/changelog-regen.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:224de5161f409a9a621ba7c26af352cf7b204e7a6de4307b0150c9941db38b69"
}

default ".github/workflows/changelog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:364e27010334331c58e86fce64b94fdcbd8a22003e31765847017f07e468faf8"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:1789341a42632af6acb115ede669f0f215e3b6f2a19a44107e352c4a556be2bd"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:64745d904a21ca7392b3bfb018e0dd936ee87b9a5251bce22b4ff3874665784b"
}

default ".gitignore" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:75b4556cafa19021cd6094d20ef78be396dabdf350282ac084ed9f012ec3c1af"
}

default ".markdownlint.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c109f82759d9451b3060f5e8e1cb07752aca359faea7bc6057e61dd7eb7f20b7"
}

default ".prettierrc.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:265dc1424b9b6aeb0edab3e6a0e60302b7595a3fa2feb0c4656458967b841d23"
}

default ".yamlfmt.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:731740b1cb919db6cb1c7e26caafc4902a5a0d8d16729ac698227192b40ae473"
}

default "CONTRIBUTING.md.tmpl" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:f8964a5a76b50e3fb5d5b055c68d2205adff5a796cee2fc1d23acc81cdf4d4e8"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d277e9c0c46044cbdcce4783810bf1296bce51d79557f651bb4938c2b2a18f19"
}

default "mise.toml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:307d630624d64b0b45236de0dfb752bc6472478f2237d53c1f95805c897511fd"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9a67e59fc7ea35194415b9ad246d14cc3296aa1a588d01a24ac7ea7784ecdcb3"
}

default ".codecov.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:311b162fa20c0b4bf8c5e84c5d86786c9ae7a296216e4c0ebe038bb6153144b4"
}

default ".github/dependabot.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:83ecabd7a4689bbef3cb8ba512f91c1ad2176a9121a0daab7a7adb4e6855f210"
}

default ".github/workflows/codeql.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:650ac701d9850da0bf781c197b2e7cfd0295d0eaf6414073ec8d6b5da073bf0e"
}

default ".github/workflows/dependabot-severity-label.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:331019181284ad68d156474cb7fd3ffe17453943d68b6e76df0f5c931481a6cc"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fdbc23ba9b8bf9c962bfc492acd98806018d845c212534519c4a0ef81e8dad23"
}

default ".github/workflows/security.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a8e9146925097d1c9b0049014c299c021a5dfab73322864a2019447f85500f38"
}

default ".golangci.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:57d9bfb542912e3507eeff1431affe3b0e1e088f8ed69d4d4143f18dcf660dd5"
}

default "CHANGELOG.md" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b64a7868c1db77e87d899af1d46c8c12d19a8c39d0b3b9a43753f75c1a0718aa"
}

default "cmd/$${project_name}/main.go.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
}

default "internal/.gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}
