#!/usr/bin/env bash
# booty launcher for cluster homelab — generated by
# "bootstrap talos emit". Do not edit: re-emitting overwrites this file.
#
# Copy this whole directory to the booty host and run this script there.
# The flags below are load-bearing:
#
#   --net=host      real PXE needs it. DHCP is broadcast and TFTP moves
#                   to a fresh port per transfer; neither survives a
#                   bridge NAT.
#   --user 0:0      under host networking the nonroot image cannot bind
#                   69/67/4011. Grant the unprivileged-port sysctl
#                   instead if you would rather not run as root.
#   --catalog       the flag is --catalog. booty's own walkthrough says
#                   --catalog-dir, which does not parse.
#   --templates-dir the overlay holding this cluster's complete,
#                   secret-bearing machineconfig templates.
#
# booty loads the catalog and templates ONCE at startup: after every
# re-emit, restart this container.
#
# Override the image with BOOTY_IMAGE=... if you need a different build.
set -euo pipefail

IMAGE="${BOOTY_IMAGE:-ghcr.io/donaldgifford/booty:v0.2.1}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly IMAGE HERE

exec docker run --rm --name booty \
  --net=host \
  --user 0:0 \
  --volume "${HERE}/catalog:/catalog:ro" \
  --volume "${HERE}/templates:/templates:ro" \
  --volume "${HERE}/boot:/boot:ro" \
  "${IMAGE}" \
  serve \
  --catalog /catalog \
  --templates-dir /templates \
  --boot-dir /boot \
  --url http://10.0.10.5:8080 \
  --proxydhcp \
  --server-ip 10.0.10.5
