package emit

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/donaldgifford/booty/render"
	"github.com/donaldgifford/hoomlab/tools/bootstrap/internal/config"
)

// The machineconfig overlay paths. The family subdirectory is
// mandatory: booty parses an overlay with the pattern "*/*" and looks
// templates up by base name, so a flat layout matches nothing and a
// matching base name replaces booty's secret-less built-in.
const (
	controlPlaneTemplatePath = "talos/controlplane.yaml.tmpl"
	workerTemplatePath       = "talos/worker.yaml.tmpl"
)

// The remaining emitted paths, relative to the emit root.
const (
	embedIPXEPath = "embed.ipxe"
	runScriptPath = "booty-run.sh"
)

// defaultBootyVersion pins the booty container image in the emitted
// launcher when the config doesn't: the release this CLI was developed
// and tested against (IMPL-0001 OQ-4).
const defaultBootyVersion = "v0.2.1"

// bootyImage returns the container image reference for the emitted
// launcher.
//
// booty's git tags carry a leading "v" but its GHCR tags do not
// (ghcr.io/donaldgifford/booty:0.2.1, never :v0.2.1), so the "v" is
// stripped. Operators reach for the release version they see on the
// releases page, and an image reference that doesn't resolve fails at
// the worst moment — on the booty host, after the tree has been copied
// over, with `docker run` reporting only "not found".
func bootyImage(booty config.Booty) string {
	version := booty.Version
	if version == "" {
		version = defaultBootyVersion
	}
	return "ghcr.io/donaldgifford/booty:" + strings.TrimPrefix(version, "v")
}

// renderEmbedIPXE renders the chainloading script that gets baked into
// ipxe.efi. It comes from booty's own renderer rather than a copy of
// the script: the embedded chain and the one booty serves at
// /boot.ipxe must agree, and the only way to guarantee that is to ask
// booty.
func renderEmbedIPXE(baseURL string) ([]byte, error) {
	r, err := render.New()
	if err != nil {
		return nil, fmt.Errorf("construct booty renderer: %w", err)
	}
	script, err := r.ChainScript(baseURL)
	if err != nil {
		return nil, fmt.Errorf("render chain script: %w", err)
	}
	return []byte(script), nil
}

// runScriptData is the model for the booty-run.sh template.
type runScriptData struct {
	ClusterName string
	Image       string
	BootyURL    string
	ServerIP    string
}

// renderRunScript renders the ready-to-run booty launcher.
func renderRunScript(cluster *config.Cluster) ([]byte, error) {
	bootyURL := cluster.Talos.Booty.URL
	u, err := url.Parse(bootyURL)
	if err != nil {
		return nil, fmt.Errorf("parse booty url %q: %w", bootyURL, err)
	}
	return renderText(runScriptPath, runScriptTemplate, runScriptData{
		ClusterName: cluster.Name,
		Image:       bootyImage(cluster.Talos.Booty),
		BootyURL:    bootyURL,
		ServerIP:    u.Hostname(),
	})
}

// The launcher encodes the operational facts that are easy to get
// wrong, with the reasons attached — an operator who hits one of these
// in the field should find the answer in the script rather than
// rediscovering it.
const runScriptTemplate = `#!/usr/bin/env bash
# booty launcher for cluster {{ .ClusterName }} — generated by
# "bootstrap talos emit". Do not edit: re-emitting overwrites this file.
#
# Copy this whole directory to the booty host and run this script there.
# The flags below are load-bearing:
#
#   --net=host      real PXE needs it. DHCP is broadcast and TFTP moves
#                   to a fresh port per transfer; neither survives a
#                   bridge NAT.
#   --user 0:0      under host networking the nonroot image cannot bind
#                   69/67/4011. Grant the unprivileged-port sysctl
#                   instead if you would rather not run as root.
#   --catalog       the flag is --catalog. booty's own walkthrough says
#                   --catalog-dir, which does not parse.
#   --templates-dir the overlay holding this cluster's complete,
#                   secret-bearing machineconfig templates.
#
# booty loads the catalog and templates ONCE at startup: after every
# re-emit, restart this container.
#
# Override the image with BOOTY_IMAGE=... if you need a different build.
set -euo pipefail

IMAGE="${BOOTY_IMAGE:-{{ .Image }}}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly IMAGE HERE

exec docker run --rm --name booty \
  --net=host \
  --user 0:0 \
  --volume "${HERE}/catalog:/catalog:ro" \
  --volume "${HERE}/templates:/templates:ro" \
  --volume "${HERE}/boot:/boot:ro" \
  "${IMAGE}" \
  serve \
  --catalog /catalog \
  --templates-dir /templates \
  --boot-dir /boot \
  --url {{ .BootyURL }} \
  --proxydhcp \
  --server-ip {{ .ServerIP }}
`
