package emit

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/donaldgifford/hoomlab/tools/bootstrap/internal/config"
	"github.com/donaldgifford/hoomlab/tools/bootstrap/internal/talos"
)

// The catalog file names. booty loads every *.hcl in the directory and
// merges them, so the numeric prefixes are ordering for humans only.
const (
	variablesPath = "catalog/00-variables.hcl"
	profilesPath  = "catalog/10-profiles.hcl"
	groupsPath    = "catalog/20-groups.hcl"
)

// profileFor maps a config role to the catalog profile that boots it.
func profileFor(role config.Role) string {
	if role == config.RoleWorker {
		return "talos-worker"
	}
	return "talos-control"
}

// catalogData is the model for the three catalog templates.
type catalogData struct {
	ClusterName  string
	TalosVersion string
	InstallImage string
	BootyURL     string
	Profiles     []catalogProfile
	Nodes        []catalogGroup
}

// catalogProfile is one boot recipe: a role and the machineconfig
// template that serves it.
type catalogProfile struct {
	Name     string
	Role     string
	Template string
}

// catalogGroup binds one VM to a profile by MAC.
type catalogGroup struct {
	Name    string
	Profile string
	MAC     string
}

// renderCatalog renders the three catalog files for the cluster.
func renderCatalog(cluster *config.Cluster) (map[string]File, error) {
	data := catalogData{
		ClusterName:  cluster.Name,
		TalosVersion: cluster.Talos.Version,
		InstallImage: talos.InstallImage(cluster.Talos.SchematicID, cluster.Talos.Version),
		BootyURL:     cluster.Talos.Booty.URL,
		Profiles: []catalogProfile{
			{Name: "talos-control", Role: string(config.RoleControlPlane), Template: controlPlaneTemplatePath},
			{Name: "talos-worker", Role: string(config.RoleWorker), Template: workerTemplatePath},
		},
	}
	data.Nodes = make([]catalogGroup, 0, len(cluster.Talos.Nodes))
	for i := range cluster.Talos.Nodes {
		n := &cluster.Talos.Nodes[i]
		data.Nodes = append(data.Nodes, catalogGroup{
			Name:    n.Name,
			Profile: profileFor(n.Role),
			MAC:     n.MAC,
		})
	}

	out := make(map[string]File, 3)
	for path, text := range map[string]string{
		variablesPath: variablesTemplate,
		profilesPath:  profilesTemplate,
		groupsPath:    groupsTemplate,
	} {
		rendered, err := renderText(path, text, data)
		if err != nil {
			return nil, err
		}
		out[path] = File{Data: rendered}
	}
	return out, nil
}

// renderText executes one of this package's templates. The templates
// are compiled in, so a parse failure is a programming error, not
// operator input — but it still travels as an error rather than a
// panic.
func renderText(name, text string, data any) ([]byte, error) {
	t, err := template.New(name).Parse(text)
	if err != nil {
		return nil, fmt.Errorf("parse %s template: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render %s: %w", name, err)
	}
	return buf.Bytes(), nil
}

// Every variable and local below is load-bearing: a generated file that
// declares values nothing reads is a lie waiting to drift, so the
// cluster name lives in the header comment rather than in an unused
// variable.
const variablesTemplate = `# booty catalog for cluster {{ .ClusterName }} — generated by
# "bootstrap talos emit". Do not edit: re-emitting overwrites this
# file. Change the bootstrap config and re-run instead.
#
# booty loads every *.hcl in this directory and merges them; the 00/10/20
# split is organizational.

variable "talos_version" {
  description = "Talos release these machines boot"
  default     = "{{ .TalosVersion }}"
}

variable "install_image" {
  description = "Talos Image Factory installer image the machineconfigs install"
  default     = "{{ .InstallImage }}"
}

variable "booty_url" {
  description = "Base URL this booty server is reachable at"
  default     = "{{ .BootyURL }}"
}

locals {
  boot_base = "talos/${var.talos_version}"

  # Talos requires these arguments on metal. A node boots without them,
  # which is exactly why their absence goes unnoticed.
  # https://docs.siderolabs.com/talos/v1.13/platform-specific-installations/bare-metal-platforms/pxe
  common_cmdline = [
    "console=ttyS0,115200n8",
    "console=tty0",
    "talos.platform=metal",
    "init_on_alloc=1",
    "slab_nomerge",
    "pti=on",
  ]
}
`

const profilesTemplate = `# Boot recipes, one per Talos role — generated by "bootstrap talos
# emit". Do not edit. Groups (20-groups.hcl) bind machines to these.
#
# The machineconfig templates these profiles render are COMPLETE,
# machinery-generated configs carrying this cluster's secrets, not
# booty's secret-less built-ins. They consume exactly two variables:
# install_image (here) and hostname (per group).
{{ range .Profiles }}
profile "{{ .Name }}" {
  boot {
    kernel = "${local.boot_base}/vmlinuz"
    initrd = "${local.boot_base}/initramfs.xz"
    # $${mac} is HCL's escape for a literal ${mac}: it must survive HCL
    # untouched so iPXE substitutes the booting machine's MAC at boot
    # time.
    cmdline = concat(local.common_cmdline, ["talos.config=${var.booty_url}/machine-config?mac=$${mac}"])
  }
  render {
    kind     = "talos-machineconfig"
    template = "{{ .Template }}"
  }
  vars = {
    role          = "{{ .Role }}"
    install_image = var.install_image
  }
}
{{ end -}}
`

const groupsTemplate = `# One group per Talos VM, pinned by MAC — generated by "bootstrap
# talos emit". Do not edit.
#
# The MAC comes from the bootstrap config, the same value the VM's NIC
# is created with, so the PXE identity binding agrees with the
# hypervisor by construction. Selector keys are a closed set: an unknown
# key silently never matches.
#
# hostname is the per-node variable the machineconfig template consumes.
{{ range .Nodes }}
group "{{ .Name }}" {
  profile = "{{ .Profile }}"
  selector = {
    mac = "{{ .MAC }}"
  }
  vars = {
    hostname = "{{ .Name }}"
  }
}
{{ end -}}
`
