# booty catalog for cluster homelab — generated by
# "bootstrap talos emit". Do not edit: re-emitting overwrites this
# file. Change the bootstrap config and re-run instead.
#
# booty loads every *.hcl in this directory and merges them; the 00/10/20
# split is organizational.

variable "talos_version" {
  description = "Talos release these machines boot"
  default     = "v1.13.8"
}

variable "booty_url" {
  description = "Base URL this booty server is reachable at"
  default     = "http://10.0.10.5:8080"
}

locals {
  boot_base = "talos/${var.talos_version}"

  # Talos requires these arguments on metal. A node boots without them,
  # which is exactly why their absence goes unnoticed.
  # https://docs.siderolabs.com/talos/v1.13/platform-specific-installations/bare-metal-platforms/pxe
  common_cmdline = [
    "console=ttyS0,115200n8",
    "console=tty0",
    "talos.platform=metal",
    "init_on_alloc=1",
    "slab_nomerge",
    "pti=on",
  ]
}
