# Boot recipes, one per node class (role × image schematic) —
# generated by "bootstrap talos emit". Do not edit. Groups
# (20-groups.hcl) bind machines to these.
#
# The machineconfig templates these profiles render are COMPLETE,
# machinery-generated configs carrying this cluster's secrets, not
# booty's secret-less built-ins. They consume exactly two variables:
# install_image (here) and hostname (per group). The kernel,
# initramfs, and installer image all carry the class's Image Factory
# schematic — the extensions are baked in at that address.

profile "talos-control" {
  boot {
    kernel = "${local.boot_base}/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/vmlinuz"
    initrd = "${local.boot_base}/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/initramfs.xz"
    # $${mac} is HCL's escape for a literal ${mac}: it must survive HCL
    # untouched so iPXE substitutes the booting machine's MAC at boot
    # time.
    cmdline = concat(local.common_cmdline, ["talos.config=${var.booty_url}/machine-config?mac=$${mac}"])
  }
  render {
    kind     = "talos-machineconfig"
    template = "talos/controlplane.yaml.tmpl"
  }
  vars = {
    role          = "controlplane"
    install_image = "factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.13.8"
  }
}

profile "talos-worker" {
  boot {
    kernel = "${local.boot_base}/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/vmlinuz"
    initrd = "${local.boot_base}/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/initramfs.xz"
    # $${mac} is HCL's escape for a literal ${mac}: it must survive HCL
    # untouched so iPXE substitutes the booting machine's MAC at boot
    # time.
    cmdline = concat(local.common_cmdline, ["talos.config=${var.booty_url}/machine-config?mac=$${mac}"])
  }
  render {
    kind     = "talos-machineconfig"
    template = "talos/worker.yaml.tmpl"
  }
  vars = {
    role          = "worker"
    install_image = "factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.13.8"
  }
}
