# Boot recipes, one per Talos role — generated by "bootstrap talos
# emit". Do not edit. Groups (20-groups.hcl) bind machines to these.
#
# The machineconfig templates these profiles render are COMPLETE,
# machinery-generated configs carrying this cluster's secrets, not
# booty's secret-less built-ins. They consume exactly two variables:
# install_image (here) and hostname (per group).

profile "talos-control" {
  boot {
    kernel = "${local.boot_base}/vmlinuz"
    initrd = "${local.boot_base}/initramfs.xz"
    # $${mac} is HCL's escape for a literal ${mac}: it must survive HCL
    # untouched so iPXE substitutes the booting machine's MAC at boot
    # time.
    cmdline = concat(local.common_cmdline, ["talos.config=${var.booty_url}/machine-config?mac=$${mac}"])
  }
  render {
    kind     = "talos-machineconfig"
    template = "talos/controlplane.yaml.tmpl"
  }
  vars = {
    role          = "controlplane"
    install_image = var.install_image
  }
}

profile "talos-worker" {
  boot {
    kernel = "${local.boot_base}/vmlinuz"
    initrd = "${local.boot_base}/initramfs.xz"
    # $${mac} is HCL's escape for a literal ${mac}: it must survive HCL
    # untouched so iPXE substitutes the booting machine's MAC at boot
    # time.
    cmdline = concat(local.common_cmdline, ["talos.config=${var.booty_url}/machine-config?mac=$${mac}"])
  }
  render {
    kind     = "talos-machineconfig"
    template = "talos/worker.yaml.tmpl"
  }
  vars = {
    role          = "worker"
    install_image = var.install_image
  }
}
