# One group per Talos VM, pinned by MAC — generated by "bootstrap
# talos emit". Do not edit.
#
# The MAC comes from the bootstrap config, the same value the VM's NIC
# is created with, so the PXE identity binding agrees with the
# hypervisor by construction. Selector keys are a closed set: an unknown
# key silently never matches.
#
# hostname is the per-node variable the machineconfig template consumes.

group "cp-01" {
  profile = "talos-control"
  selector = {
    mac = "02:50:99:a2:00:01"
  }
  vars = {
    hostname = "cp-01"
  }
}

group "cp-02" {
  profile = "talos-control"
  selector = {
    mac = "02:50:99:a2:00:02"
  }
  vars = {
    hostname = "cp-02"
  }
}

group "worker-01" {
  profile = "talos-worker"
  selector = {
    mac = "02:50:99:a2:01:01"
  }
  vars = {
    hostname = "worker-01"
  }
}
