// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package talosmocks

import (
	"context"
	"log/slog"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function for the type MockClient
func (_mock *MockClient) Bootstrap(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockClient_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Bootstrap(ctx any) *MockClient_Bootstrap_Call {
	return &MockClient_Bootstrap_Call{Call: _e.mock.On("Bootstrap", ctx)}
}

func (_c *MockClient_Bootstrap_Call) Run(run func(ctx context.Context)) *MockClient_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Bootstrap_Call) Return(err error) *MockClient_Bootstrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Bootstrap_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EtcdMemberList provides a mock function for the type MockClient
func (_mock *MockClient) EtcdMemberList(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EtcdMemberList")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_EtcdMemberList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EtcdMemberList'
type MockClient_EtcdMemberList_Call struct {
	*mock.Call
}

// EtcdMemberList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) EtcdMemberList(ctx any) *MockClient_EtcdMemberList_Call {
	return &MockClient_EtcdMemberList_Call{Call: _e.mock.On("EtcdMemberList", ctx)}
}

func (_c *MockClient_EtcdMemberList_Call) Run(run func(ctx context.Context)) *MockClient_EtcdMemberList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_EtcdMemberList_Call) Return(strings []string, err error) *MockClient_EtcdMemberList_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockClient_EtcdMemberList_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockClient_EtcdMemberList_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockClient
func (_mock *MockClient) Health(ctx context.Context, timeout time.Duration, log *slog.Logger) error {
	ret := _mock.Called(ctx, timeout, log)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, timeout, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockClient_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
//   - log *slog.Logger
func (_e *MockClient_Expecter) Health(ctx any, timeout any, log any) *MockClient_Health_Call {
	return &MockClient_Health_Call{Call: _e.mock.On("Health", ctx, timeout, log)}
}

func (_c *MockClient_Health_Call) Run(run func(ctx context.Context, timeout time.Duration, log *slog.Logger)) *MockClient_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 *slog.Logger
		if args[2] != nil {
			arg2 = args[2].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Health_Call) Return(err error) *MockClient_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Health_Call) RunAndReturn(run func(ctx context.Context, timeout time.Duration, log *slog.Logger) error) *MockClient_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Kubeconfig provides a mock function for the type MockClient
func (_mock *MockClient) Kubeconfig(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Kubeconfig")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Kubeconfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kubeconfig'
type MockClient_Kubeconfig_Call struct {
	*mock.Call
}

// Kubeconfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Kubeconfig(ctx any) *MockClient_Kubeconfig_Call {
	return &MockClient_Kubeconfig_Call{Call: _e.mock.On("Kubeconfig", ctx)}
}

func (_c *MockClient_Kubeconfig_Call) Run(run func(ctx context.Context)) *MockClient_Kubeconfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Kubeconfig_Call) Return(bytes []byte, err error) *MockClient_Kubeconfig_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockClient_Kubeconfig_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockClient_Kubeconfig_Call {
	_c.Call.Return(run)
	return _c
}
